name: Build Executables

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-15-intel']

    env:
      MAIN_PY_FILE: 'gui.py'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.x

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
      working-directory: ./

    - name: Build executable
      run: |
        pyinstaller --onefile ${{ env.MAIN_PY_FILE }}
      working-directory: ./

    - name: Create macOS Double-Clickable Script & Zip
      if: matrix.os == 'macos-15-intel'
      run: |
        cd dist
        echo '#!/bin/sh' > LaunchApp.command
        echo 'DIR=$(dirname "$0")' >> LaunchApp.command
        echo 'cd "$DIR"' >> LaunchApp.command
        echo './gui' >> LaunchApp.command
        chmod +x LaunchApp.command
        zip -r ../gui_mac.zip gui LaunchApp.command
      working-directory: ./

    - name: Create Artifact (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: windows-executables
        path: dist/

    - name: Create Artifact (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: linux-executables
        path: dist/

    - name: Create Artifact (macOS)
      if: matrix.os == 'macos-15-intel'
      uses: actions/upload-artifact@v4
      with:
        name: macos-executables
        path: gui_mac.zip

    - name: List files in dist folder
      run: ls -R ./dist/
